# 5.6 try语句块和异常处理

- C++中的异常处理机制包括：

  - **throw表达式**，异常检测部分使用throw表达式来引发(raise)异常。
  - **try-catch语句块**，try语句中通常包含throw表达式来抛出异常，这些异常通常被某个catch子句处理。
  - 一套**异常类**，用于在throw表达式和相关的catch子句直接传递异常的具体信息。

- 在复杂的系统中，程序在遇到抛出异常的代码前，其执行路劲可能已经经过了多个try-catch语句块。例如，一个try-catch语句块可能调用了包含另一个try-catch语句块的函数，新的try-catch语句块又调用了一个这样的函数，以此类推。寻找处理代码的过程与函数调用链恰好相反，当异常被抛出时，首先搜索抛出该异常的函数，如果没找到匹配的catch语句，则终止该函数，然后在调用它的上层函数中查找，逐层回退。如果最终仍然没有找到对应的catch语句，程序转到名为**terminate**的标准库函数。

- C++标准库定义了一组类，用于报告标准库函数遇到的问题。这些异常类也可以在用户编写的程序中使用，它们分别定义在4个头文件中：

  - exception头文件定义了最通用的异常类exception。它只报告异常的发生，不提供任何额外信息。
  - stdexcept头文件定义了几种常见的异常类，查表。
  - new头文件定义了bad_alloc异常类型，将在后面介绍。
  - type_info头文件定义了bad_cast异常类型，将在后面介绍。

  我们只能以默认初始化的方式初始化exception、bad_alloc和bad_cast对象，不允许为这些对象赋初值。

  其他类型的异常则相反，应使用string对象或C风格字符串初始化这些异常对象，而不允许使用默认初始化。

